apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "helloworld-wawa"
spec:
  hosts:
    - "*"
  gateways:
    - bookinfo-gateway
  http:
    - match:
        - uri:
            prefix: /hello
      route:
        - destination:
            host: "helloworld-wawa"
            port:
              number: {{ .Values.service.port }}
