# Default values for helloworld-wawa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Image details should be provided as env variables in the CD pipeline
  repository: helloworld-wawa
  tag: latest
  pullPolicy: IfNotPresent
  #pullSecrets: secret for the image repo

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9090
  healthPort: 9002
  #nodePort: 30036

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - helloworld-wawa
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
#  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}