apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-wawa
spec:
  host: helloworld-wawa
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1