apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld-wawa.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "helloworld-wawa.name" . }}
    helm.sh/chart: {{ include "helloworld-wawa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      #targetPort: {{ .Values.service.port }}
      #protocol: TCP
      name: http
      #nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "helloworld-wawa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
